apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fe
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fe
    spec:
      containers:
      - image: nginx:1.27.1
        name: nginx
        resources: {}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume-nginx
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: config-volume-nginx
        configMap:
          name: nginx-config
status: {}
